### ISSUE TITLE
Add Asset Key Thief

### ISSUE THREAD

**Issue by 0xdabbad00** [wiz-sec/open-cvdb#170]
This issue, impacting GCP, allowed someone with the permission`cloudasset.assets.searchAllResources` to use the Cloud Asset Inventory API to read Google Cloud Service Account private keys.  This is privilege escalation so this should have a severity of Medium (or possibly High). 

https://engineering.sada.com/asset-key-thief-disclosure-cfae4f1778b6

**Comment by amccarthy-figma** [comment]
https://www.cloudvulndb.org/asset-key-thief?

**Comment by 0xdabbad00** [comment]
Oof, good catch. Thank you.
