### ISSUE TITLE
[Contribution] GCP CloudSQL Vulnerability Leads to Internal Container Access and Data Exposure

### ISSUE THREAD

**Issue by korniko98** [wiz-sec/open-cvdb#220]
## Summary (give a brief description of the issue)
Escalating from a basic CloudSQL user to full-fledged sysadmin on the container.

## References (provide links to blogposts, etc.)
https://www.dig.security/post/gcp-cloudsql-vulnerability-leads-to-internal-container-access-and-data-exposure

**Comment by ramimac** [comment]
https://www.cloudvulndb.org/cloudsql-privesc already included / dupe
