### ISSUE TITLE
[Contribution] Add security issue or vulnerability

### ISSUE THREAD

**Issue by julienr78** [wiz-sec/open-cvdb#274]
## Summary (give a brief description of the issue)
AWS WAF SSRF Rule bypass

## References (provide links to blogposts, etc.)
https://medium.com/@bcksec/behind-the-firewall-bypassing-aws-wafs-ssrf-managed-rules-3671a789c815

**Comment by korniko98** [comment]
hi @julienr78, WAF bypasses are out of scope of this database - please see our [contribution guidelines](https://www.cloudvulndb.org/about).
