### ISSUE TITLE
Add an RSS feed to the website

### ISSUE THREAD

**Issue by Drag0nR3b0rn** [wiz-sec/open-cvdb#38]
RSS is a format that allows users and applications to access updates to websites in a standardized, computer-readable way. Adding a RSS feed of newly added and updated vulnerabilities to the website will allow cloud security teams to easier get push notification on new vulnerabilities added to the open-cvdb using their existing workflows based on RSS, and easily integrate open-cvdb into their threatintel pipelines.

**Comment by KingBain** [comment]
Although not ideal, it is fairly easy to use one of the sitescrape-to-rss sites to generate your own RSS feed. 

https://politepol.com/fd/EJHYP7y2bm1s

**Comment by korniko98** [comment]
RSS added - https://www.cloudvulndb.org/rss/feed.xml
